
[origins]

	[origins."origins:enderian"]
		enabled = true
		"origins:throw_ender_pearl" = true
		"origins:water_vulnerability" = true
		"origins:pumpkin_hate" = true
		"origins:extra_reach" = true
		"origins:ender_particles" = true
		"origins:damage_from_potions" = true

	[origins."origins:feline"]
		enabled = true
		"origins:fall_immunity" = true
		"origins:sprint_jump" = true
		"origins:velvet_paws" = true
		"origins:nine_lives" = true
		"origins:weak_arms" = true
		"origins:scare_creepers" = true
		"origins:cat_vision" = true

	[origins."medievalorigins:dwarf"]
		enabled = true
		"medievalorigins:dwarf/dwarven_tech" = true
		"medievalorigins:dwarf/miniature" = true
		"medievalorigins:dwarf/nocturnal_eyes" = true
		"medievalorigins:dwarf/darkness_dweller" = true
		"medievalorigins:dwarf/dense" = true
		"medievalorigins:dwarf/potent_brew" = true
		"medievalorigins:dwarf/mythril_resonance" = true
		"medievalorigins:dwarf/pickaxeless_stone" = true
		"medievalorigins:dwarf/helmet_spawn" = true

	[origins."origins:elytrian"]
		enabled = true
		"origins:elytra" = true
		"origins:launch_into_air" = true
		"origins:aerial_combatant" = true
		"origins:light_armor" = true
		"origins:claustrophobia" = true
		"origins:more_kinetic_damage" = true

	[origins."medievalorigins:pixie"]
		enabled = true
		"medievalorigins:pixie/flight" = true
		"medievalorigins:pixie/pixie_properties" = true
		"medievalorigins:pixie/feather_footed" = true
		"medievalorigins:pixie/wings" = true
		"medievalorigins:pixie/mount" = true
		"medievalorigins:pixie/good_fortunes" = true
		"medievalorigins:pixie/mischief_maketh_man" = true
		"medievalorigins:pixie/curse_of_flight" = true
		"medievalorigins:pixie/soaked" = true
		"medievalorigins:pixie/troublemaker" = true

	[origins."medievalorigins:high_elf"]
		enabled = true
		"medievalorigins:high_elf/ebonbreath" = true
		"medievalorigins:high_elf/fragile" = true
		"medievalorigins:high_elf/glacial_step" = true
		"medievalorigins:high_elf/spell_power_irons" = true
		"medievalorigins:high_elf/elegant" = true
		"medievalorigins:high_elf/blazenbreath" = true
		"medievalorigins:high_elf/void_warp" = true
		"medievalorigins:high_elf/extrusive_movement" = true
		"medievalorigins:high_elf/instant_cure" = true
		"medievalorigins:high_elf/mystic_affinity" = true
		"medievalorigins:high_elf/towering" = true
		"medievalorigins:high_elf/blazenbreath_weak" = true
		"medievalorigins:high_elf/gear_spawn" = true

	[origins."medievalorigins:plague_victim"]
		enabled = true
		"medievalorigins:plague_victim/foul_aura" = true
		"medievalorigins:plague_victim/plague_immunity" = true
		"medievalorigins:plague_victim/risk_of_transmission" = true
		"medievalorigins:plague_victim/contagious" = true
		"medievalorigins:plague_victim/insomniac" = true
		"medievalorigins:plague_victim/sensitive_skin" = true
		"medievalorigins:plague_victim/skin_and_bones" = true
		"origins_survive:illness_resistance" = true

	[origins."magic_origins:pirate"]
		enabled = true
		"magic_origins:pirate/hook" = true
		"magic_origins:pirate/eye_patch" = true
		"magic_origins:pirate/swim_speed" = true
		"magic_origins:pirate/home" = true
		"magic_origins:pirate/shiny" = true
		"magic_origins:advancement" = true

	[origins."medievalorigins:revenant"]
		enabled = true
		"medievalorigins:revenant/cronch" = true
		"medievalorigins:revenant/transfer_item" = true
		"medievalorigins:revenant/skeleton_summons" = true
		"medievalorigins:revenant/zombie_summons" = true
		"medievalorigins:revenant/putrid_communion" = true
		"medievalorigins:revenant/hellraiser" = true
		"medievalorigins:revenant/siphon" = true
		"medievalorigins:revenant/unwitherable" = true
		"medievalorigins:revenant/undeadge" = true
		"medievalorigins:revenant/poor_reputation" = true
		"medievalorigins:revenant/black_thumb" = true
		"medievalorigins:revenant/disturbed" = true
		"medievalorigins:revenant/unguarded" = true
		"origins_survive:sleepless" = true

	[origins."magic_origins:hydra"]
		enabled = true
		"magic_origins:hydra/heads" = true
		"magic_origins:hydra/passive_head_powers" = true
		"magic_origins:hydra/scales" = true
		"magic_origins:hydra/no_fire_durability" = true
		"magic_origins:hydra/fire_breath" = true
		"magic_origins:hydra/ability_toggle" = true
		"magic_origins:hydra/water_ray" = true
		"magic_origins:hydra/poison_breath" = true
		"magic_origins:hydra/wind_wave" = true
		"magic_origins:hydra/helmet" = true
		"magic_origins:advancement" = true

	[origins."magic_origins:panda"]
		enabled = true
		"magic_origins:panda/bamboo_new" = true
		"magic_origins:panda/panda_shit" = true
		"origins:vegetarian" = true
		"magic_origins:advancement" = true

	[origins."medievalorigins:banshee"]
		enabled = true
		"medievalorigins:banshee/spectral" = true
		"medievalorigins:banshee/sonic_shriek" = true
		"medievalorigins:banshee/lunar_nexus" = true
		"medievalorigins:banshee/dimeritium_shackles" = true
		"medievalorigins:banshee/hexed" = true
		"medievalorigins:banshee/immaterial" = true
		"medievalorigins:banshee/overwhelmed" = true
		"origins_survive:sleepless" = true

	[origins."medievalorigins:gorgon"]
		enabled = true
		"medievalorigins:gorgon/petrifying_gaze" = true
		"medievalorigins:gorgon/revenge" = true
		"medievalorigins:gorgon/hydrophobe" = true
		"medievalorigins:gorgon/to_stone" = true
		"medievalorigins:gorgon/silver_aversion" = true
		"medievalorigins:gorgon/poison_blood" = true
		"medievalorigins:gorgon/poison_immune" = true

	[origins."origins:phantom"]
		enabled = true
		"origins:phantomize" = true
		"origins:translucent" = true
		"origins:phasing" = true
		"origins:invisibility" = true
		"origins:burn_in_daylight" = true
		"origins:hunger_over_time" = true
		"origins:fragile" = true
		"origins:phantomize_overlay" = true

	[origins."magic_origins:cookie"]
		enabled = true
		"magic_origins:cookie/canibalism" = true
		"magic_origins:cookie/spillage" = true
		"magic_origins:advancement" = true

	[origins."origins:blazeborn"]
		enabled = true
		"origins:fire_immunity" = true
		"origins:nether_spawn" = true
		"origins:burning_wrath" = true
		"origins:hotblooded" = true
		"origins:water_vulnerability" = true
		"origins:flame_particles" = true
		"origins:damage_from_snowballs" = true
		"origins:damage_from_potions" = true

	[origins."magic_origins:sand_larvae"]
		enabled = true
		"magic_origins:sand/sand_larvae/air_swim" = true
		"magic_origins:sand/sand_larvae/advancement" = true
		"magic_origins:sand/sand_larvae/hp" = true
		"magic_origins:sand/sand_larvae/size" = true
		"magic_origins:sand/sand_larvae/bite" = true
		"magic_origins:sand/sand_larvae/spit" = true
		"magic_origins:sand/sand_larvae/sand_confidene" = true
		"magic_origins:sand/sand_larvae/desert" = true
		"magic_origins:advancement" = true

	[origins."medievalorigins:wood_elf"]
		enabled = true
		"medievalorigins:wood_elf/archer" = true
		"medievalorigins:wood_elf/forest_vision" = true
		"medievalorigins:wood_elf/eagle_eyed" = true
		"medievalorigins:wood_elf/towering" = true
		"medievalorigins:wood_elf/steward" = true
		"medievalorigins:wood_elf/elegant" = true
		"medievalorigins:wood_elf/graceful" = true
		"medievalorigins:wood_elf/gear_spawn" = true

	[origins."origins:avian"]
		enabled = true
		"origins:slow_falling" = true
		"origins:fresh_air" = true
		"origins:like_air" = true
		"origins:tailwind" = true
		"origins:lay_eggs" = true
		"origins:vegetarian" = true

	[origins."magic_origins:lorax"]
		enabled = true
		"magic_origins:lorax/phase" = true
		"magic_origins:lorax/no_tree_chopping" = true
		"magic_origins:lorax/size" = true
		"magic_origins:lorax/friendly" = true
		"magic_origins:lorax/marshmellow" = true
		"magic_origins:lorax/edible_marshmellow" = true
		"magic_origins:advancement" = true

	[origins."magic_origins:dwarf"]
		enabled = true
		"magic_origins:dwarf/size" = true
		"magic_origins:dwarf/haste" = true
		"magic_origins:dwarf/less_hp" = true
		"magic_origins:dwarf/stamina/sugar" = true
		"magic_origins:slow" = true
		"magic_origins:advancement" = true
		"origins:no_shield" = true
		"origins:fall_immunity" = true
		"origins:climbing" = true

	[origins."magic_origins:necromancer"]
		enabled = true
		"magic_origins:necromancer/night_buffs" = true
		"magic_origins:necromancer/night_buffs2" = true
		"magic_origins:necromancer/mysterous" = true
		"magic_origins:necromancer/emume" = true
		"magic_origins:necromancer/summon/sz_summon" = true
		"magic_origins:necromancer/summon/a_summon" = true
		"magic_origins:necromancer/summon/d_summon" = true
		"magic_origins:necromancer/cloak" = true
		"magic_origins:advancement" = true

	[origins."magic_origins:yin"]
		enabled = true
		"magic_origins:yinyang/yang/yintransform" = true
		"magic_origins:yinyang/yang/cloud" = true
		"magic_origins:yinyang/yang/posess" = true
		"magic_origins:yinyang/yang/transparency1" = true
		"magic_origins:yinyang/yang/dayweak" = true
		"magic_origins:yinyang/yang/invis_temp" = true
		"magic_origins:advancement" = true

	[origins."magic_origins:green_dragon"]
		enabled = true
		"magic_origins:green_dragon/discount" = true
		"magic_origins:green_dragon/green" = true
		"magic_origins:green_dragon/elytra" = true
		"magic_origins:green_dragon/unbad_omen" = true
		"magic_origins:green_dragon/vegie" = true
		"magic_origins:green_dragon/food" = true
		"magic_origins:green_dragon/size" = true
		"magic_origins:green_dragon/emerald" = true
		"magic_origins:green_dragon/droar" = true
		"magic_origins:advancement" = true

	[origins."magic_origins:mimic"]
		enabled = true
		"magic_origins:mimic/toggle" = true
		"magic_origins:mimic/toggle2" = true
		"magic_origins:mimic/display" = true
		"origins:nine_lives" = true
		"magic_origins:advancement" = true

	[origins."magic_origins:undead"]
		enabled = true
		"magic_origins:undead/zombie" = true
		"magic_origins:undead/daylight" = true
		"magic_origins:undead/hugs" = true
		"magic_origins:undead/body" = true
		"magic_origins:undead/body_" = true
		"magic_origins:undead/undead" = true
		"magic_origins:undead/unnerving" = true
		"magic_origins:undead/attacker" = true
		"magic_origins:undead/target" = true
		"magic_origins:undead/join_team" = true
		"magic_origins:undead/create_team" = true
		"magic_origins:undead/summon" = true
		"magic_origins:undead/shovel" = true
		"magic_origins:undead/stone_sword" = true
		"magic_origins:advancement" = true

	[origins."medievalorigins:fae"]
		enabled = true
		"medievalorigins:fae/levitation" = true
		"medievalorigins:fae/magic_resistance" = true
		"medievalorigins:fae/magic_damage_boost" = true
		"medievalorigins:fae/regen" = true
		"medievalorigins:fae/allure" = true
		"medievalorigins:fae/diminutive" = true
		"medievalorigins:fae/iron_aversion" = true

	[origins."origins:human"]
		enabled = true

	[origins."medievalorigins:goblin"]
		enabled = true
		"medievalorigins:goblin/greedy" = true
		"medievalorigins:goblin/green" = true
		"medievalorigins:goblin/durability" = true
		"medievalorigins:goblin/cunning" = true
		"medievalorigins:goblin/nippy" = true
		"medievalorigins:goblin/stunted" = true
		"medievalorigins:goblin/frail" = true

	[origins."medievalorigins:moon_elf"]
		enabled = true
		"medievalorigins:moon_elf/moonlight_rogue" = true
		"medievalorigins:moon_elf/stealth" = true
		"medievalorigins:moon_elf/ethereal" = true
		"medievalorigins:moon_elf/crazed" = true
		"medievalorigins:moon_elf/elegant" = true
		"medievalorigins:moon_elf/nimble" = true
		"medievalorigins:moon_elf/fragile" = true
		"medievalorigins:moon_elf/towering" = true
		"origins_survive:sleepless" = true

	[origins."medievalorigins:yeti"]
		enabled = true
		"medievalorigins:yeti/frigid_pulse" = true
		"medievalorigins:yeti/from_whence_you_came" = true
		"medievalorigins:yeti/frosty_breath" = true
		"medievalorigins:yeti/titanic" = true
		"medievalorigins:yeti/unstoppable" = true
		"medievalorigins:yeti/winter_body" = true
		"medievalorigins:yeti/flammable" = true
		"medievalorigins:yeti/thick_fur" = true
		"origins_survive:cold_resistance" = true

	[origins."medievalorigins:siren"]
		enabled = true
		"medievalorigins:siren/siren_song" = true
		"medievalorigins:siren/amphibious" = true
		"medievalorigins:siren/holy_water" = true
		"medievalorigins:siren/out_of_your_depth" = true
		"medievalorigins:siren/prone" = true
		"medievalorigins:siren/flammable" = true
		"medievalorigins:siren/water_vision" = true
		"medievalorigins:siren/seduce" = true
		"mermod:fabulous_fins" = true
		"survive:cold_blooded" = true
		"origins:aquatic" = true

	[origins."medievalorigins:incubus"]
		enabled = true
		"medievalorigins:incubus/demon_fire" = true
		"medievalorigins:incubus/hellborne" = true
		"medievalorigins:incubus/carnivore" = true
		"medievalorigins:incubus/unholy_deal" = true
		"medievalorigins:incubus/hydrophobe" = true
		"medievalorigins:incubus/impure" = true
		"medievalorigins:incubus/dimension_strength" = true
		"medievalorigins:incubus/lava_swim" = true
		"medievalorigins:incubus/red" = true
		"origins:nether_spawn" = true
		"origins_survive:lava_drinker" = true
		"origins_survive:heat_resistance" = true

	[origins."magic_origins:red_dragon"]
		enabled = true
		"origins:fire_immunity" = true
		"origins:nether_spawn" = true
		"origins:burning_wrath" = true
		"origins:water_vulnerability" = true
		"origins:hotblooded" = true
		"magic_origins:red_dragon/freeze" = true
		"magic_origins:red_dragon/size69" = true
		"magic_origins:red_dragon/wreckless" = true
		"origins:carnivore" = true
		"magic_origins:advancement" = true

	[origins."origins:shulk"]
		enabled = true
		"origins:shulker_inventory" = true
		"origins:natural_armor" = true
		"origins:strong_arms" = true
		"origins:strong_arms_break_speed" = true
		"origins:no_shield" = true
		"origins:more_exhaustion" = true

	[origins."origins:merling"]
		enabled = true
		"origins:water_breathing" = true
		"origins:water_vision" = true
		"origins:aqua_affinity" = true
		"origins:swim_speed" = true
		"origins:like_water" = true
		"origins:aquatic" = true
		"origins:conduit_power_on_land" = true
		"origins:air_from_potions" = true

	[origins."medievalorigins:ogre"]
		enabled = true
		"medievalorigins:ogre/gargantuan" = true
		"medievalorigins:ogre/bloodlust" = true
		"medievalorigins:ogre/ravager" = true
		"medievalorigins:ogre/lead_belly" = true
		"medievalorigins:ogre/stocky" = true
		"medievalorigins:ogre/ravenous" = true
		"medievalorigins:ogre/sluggish" = true
		"medievalorigins:ogre/unwieldy" = true
		"medievalorigins:ogre/ogre_properties" = true
		"medievalorigins:ogre/bloodlust_camera" = true
		"medievalorigins:ogre/orcish_pride" = true
		"origins_survive:illness_resistance" = true

	[origins."origins:arachnid"]
		enabled = true
		"origins:climbing" = true
		"origins:master_of_webs" = true
		"origins:carnivore" = true
		"origins:fragile" = true
		"origins:arthropod" = true

	[origins."medievalorigins:alfiq"]
		enabled = true
		"medievalorigins:alfiq/clawed" = true
		"medievalorigins:alfiq/poor_grip" = true
		"medievalorigins:alfiq/agile_preference" = true
		"medievalorigins:alfiq/on_your_feet" = true
		"medievalorigins:alfiq/crepuscular" = true
		"medievalorigins:alfiq/pickpocket" = true
		"medievalorigins:alfiq/pickpocket_player" = true
		"medievalorigins:alfiq/pounce" = true
		"origins:carnivore" = true
		"origins:velvet_paws" = true
		"origins:scare_creepers" = true
		"medievalorigins:alfiq/meow" = true

	[origins."magic_origins:yang"]
		enabled = true
		"magic_origins:yinyang/yin/yangtransform" = true
		"magic_origins:yinyang/yin/heal" = true
		"magic_origins:yinyang/yin/lightning" = true
		"magic_origins:yinyang/yin/transparency" = true
		"magic_origins:yinyang/yin/darkweak" = true
		"magic_origins:advancement" = true

	[origins."magic_origins:druid"]
		enabled = true
		"magic_origins:druid/forest_buff" = true
		"magic_origins:druid/nether_burn" = true
		"magic_origins:druid/hot_debuff" = true
		"origins:vegetarian" = true
		"magic_origins:druid/roots" = true
		"magic_origins:druid/roots2" = true
		"magic_origins:druid/roots3" = true
		"magic_origins:druid/regen" = true
		"magic_origins:druid/fireweak" = true
		"magic_origins:druid/green" = true
		"magic_origins:hunger" = true
		"magic_origins:fertilize" = true
		"magic_origins:advancement" = true

	[origins."medievalorigins:troll"]
		enabled = true
		"medievalorigins:troll/ironhide" = true
		"medievalorigins:troll/ham_fisted" = true
		"medievalorigins:troll/mountainous" = true
		"medievalorigins:troll/apex_predator" = true
		"medievalorigins:troll/lumbering" = true
		"medievalorigins:troll/old_blood" = true
		"medievalorigins:troll/out_of_stock" = true
		"origins_survive:cold_resistance" = true

	[origins."magic_origins:test"]
		enabled = true

	[origins."magic_origins:kraken"]
		enabled = true
		"magic_origins:kraken/bigger_kraken" = true
		"magic_origins:kraken/tentacles" = true
		"magic_origins:kraken/wave" = true
		"magic_origins:kraken/tentacle_grap" = true
		"origins:air_from_potions" = true
		"origins:aquatiq" = true
		"origins:aqua_affinity" = true
		"origins:more_exhaustion" = true
		"origins:carnivore" = true
		"origins:water_vision" = true
		"origins:conduit_power_on_land" = true
		"origins:like_water" = true
		"origins:water_breathing" = true
		"magic_origins:advancement" = true

	[origins."magic_origins:magic_fly"]
		enabled = true
		"magic_origins:magic_fly/vegie" = true
		"magic_origins:magic_fly/fairy_wings" = true
		"magic_origins:magic_fly/forest_buffs" = true
		"magic_origins:magic_fly/size" = true
		"magic_origins:magic_fly/6hp" = true
		"magic_origins:magic_fly/no_swords" = true
		"magic_origins:magic_fly/iron_golem" = true
		"magic_origins:magic_fly/hot_debuf" = true
		"magic_origins:magic_fly/nether" = true
		"magic_origins:hunger" = true
		"magic_origins:slow" = true
		"magic_origins:heal" = true
		"magic_origins:awareness" = true
		"magic_origins:advancement" = true

	[origins."medievalorigins:arachnae"]
		enabled = true
		"medievalorigins:arachnae/climber" = true
		"medievalorigins:arachnae/many_eyes" = true
		"medievalorigins:arachnae/venomous_bite" = true
		"medievalorigins:arachnae/web_slinger" = true
		"medievalorigins:arachnae/bottomless_stomach" = true
		"medievalorigins:arachnae/brittle" = true
		"medievalorigins:arachnae/fragile_exoskeleton" = true
		"origins:master_of_webs" = true
		"origins:arthropod" = true

	[origins."magic_origins:cyborg"]
		enabled = true
		"magic_origins:cyborg/metal_skin" = true
		"magic_origins:cyborg/circuits" = true
		"magic_origins:cyborg/jump" = true
		"magic_origins:cyborg/fire_immunity" = true
		"magic_origins:cyborg/metal_skin_no_armor" = true
		"magic_origins:cyborg/iron_feet" = true
		"magic_origins:cyborg/robot_eye" = true
		"magic_origins:advancement" = true

